### ISSUE TITLE
Problem example-i2c-scanner

### ISSUE THREAD

**Issue by paoolea** [kashimAstro/ofxGPIO#12]
I try to compile "example-i2c-scanner"

In file included from ../src/ofxGPIO.h:44:0,
                 from src/main.cpp:2:
../src/readata.h: In member function ‘void ReadRawData::update()’:
../src/readata.h:353:23: warning: unused variable ‘ok’ [-Wunused-variable]
                  char ok= -1;

**Comment by kashimAstro** [comment]
Hi, this not error it only warning, are there any other problems?
