### ISSUE TITLE
PI2

### ISSUE THREAD

**Issue by antimodular** [kashimAstro/ofxGPIO#2]
would your addon work on the PI2 with OF 0.9.0 ?
thanks.

**Comment by kashimAstro** [comment]
@antimodular I'm working on porting all the addons under OF0.9
when they are short on ofxFurry I deal ofxGPIO

good day

**Comment by j3ffgray** [comment]
Any movement on updating this?

**Comment by kashimAstro** [comment]
@grayfuse I'm building the version 2 dell'addons with new examples and new more practical functions, unfortunately the work keeps me a little busy these days, I predict that within a week I throw out a beta.

new future:
https://www.youtube.com/watch?v=XuHB4FBesbY
https://www.youtube.com/watch?v=NjUIUrve93A
I keep you updated..

**Comment by j3ffgray** [comment]
Awesome, looking forward to seeing it, thanks for sharing your progress!

**Comment by kashimAstro** [comment]
hello guys @antimodular  @grayfuse,
I wanted to tell you I made a first update of ofxGPIO.

I added a bit of functionality and some new examples,
as soon as I have time I prepare a detailed wiki.

good day
