### ISSUE TITLE
unable to set direction of gpio

### ISSUE THREAD

**Issue by prismspecs** [kashimAstro/ofxGPIO#23]
When I run the example-simple-led program I get the following

```
OPERATION FAILED: Unable to set direction of GPIO2
OPERATION FAILED: Unable to set value of GPIO2
```

**Comment by kashimAstro** [comment]
Hi @prismspecs, 

you need to make sure your user has permissions,
you can use sudo or add some udev rules, look here:
https://forum.openframeworks.cc/t/ofxgpio-update-debian-stretch/28430/8?u=kashim
