### ISSUE TITLE
SPI not working in of093 and RPi2

### ISSUE THREAD

**Issue by urbanpixellab** [kashimAstro/ofxGPIO#4]
Hi tested the spi example with the connection to the adc3008 shown in the readme but i always get the error "Problem transmitting spi data..ioctl". I tried the button example and this is working fine.

Thanks in advance.

**Comment by kashimAstro** [comment]
Hi, I will make a couple of quick questions, to understand the problem...

1) you have enabled SPI? There are many ways to do it, simple mode:
  raspi-config -> Advanced Option -> SPI

2) to have a confirmation on the operation of SPI do:
lsmod | grep bcm

3) you can make a photo at the cable connection?

4) since the last update and 'added a SPI2 class that I have not tested adc3008, you are using SPI or SPI2?

thanks for the tip :)

**Comment by urbanpixellab** [comment]
1. spi is already enabled
2. snd_bcm2835            20511  1 
   snd_pcm                75698  1 snd_bcm2835
   snd                    51844  5 snd_bcm2835,snd_timer,snd_pcm
   bcm2835_wdt             3225  0 
   bcm2835_gpiomem         3040  0 
   spi_bcm2835             7286  0 
3. i am using spi, not spi2

3 pictures are in a few minutes

**Comment by urbanpixellab** [comment]
![20160613_184823](https://cloud.githubusercontent.com/assets/9715454/16016122/7df5b042-3199-11e6-9a90-48c795080893.jpg)

**Comment by kashimAstro** [comment]
you can publish your program setup that contain the "new = SPI()" ?

**Comment by urbanpixellab** [comment]
#include "ofMain.h"
#include "ofAppNoWindow.h"
#include "ofxGPIO.h"

class noWin : public ofBaseApp{
        public:
        SPI \* spi;
            int i;
            int a2dVal;
            int a2dChannel;
            unsigned char data[3];

```
    void setup(){
            i = 20;
            a2dVal = 0;
            a2dChannel = 0;
            spi = new SPI("/dev/spidev0.0", SPI_MODE_0, 1000000, 8);
    }

    void update(){
        data[0] = 1;
            data[1] = 0b10000000 |( ((a2dChannel & 7) << 4));
            data[2] = 0;

            spi->spiWriteRead(data, sizeof(data) );
            a2dVal = 0;
                a2dVal = (data[1]<< 8) & 0b1100000000;
                a2dVal |=  (data[2] & 0xff);
            sleep(2);
            ofLog()<<"Result: " << a2dVal;
    }
```

};

int main( ){
        ofAppNoWindow window;
    ofSetupOpenGL(&window, 0,0, OF_WINDOW);
    ofRunApp( new noWin() );
}

**Comment by urbanpixellab** [comment]
This is your spi example, which i am using.

**Comment by kashimAstro** [comment]
you've tried to use interface: /dev/spidev0.1  ?

**Comment by urbanpixellab** [comment]
i tried now
spi = new SPI("/dev/spidev0.1", SPI_MODE_0, 1000000, 8);

but the same error.

**Comment by kashimAstro** [comment]
I'm trying MCP3008 in the laboratory, short update you

**Comment by kashimAstro** [comment]
ok the problem exists, but appears to be closely tied to 9.x of openFrameworks paired with a combination of reading from SPI.

In fact, if you try to run this example outside openFrameworks or with a version of openFrameworks < 9.x running fine.

I am attaching an example in C ++ to use without openFrameworks.
extract the zip file in the /home/pi/
cd mcp3008/
make
./main

[mcp3008.zip](https://github.com/kashimAstro/ofxGPIO/files/314321/mcp3008.zip)

let me know if this example outside openFrameworks works for you.
in a while I try to figure out the problem, I leave this open.

**Comment by urbanpixellab** [comment]
wow, thank you for this example, this is working.

**Comment by xumo** [comment]
Have you solved this issue yet?

**Comment by kashimAstro** [comment]
hello @xumo , I'm sorry I fix this in September I am now out for work.

**Comment by xumo** [comment]
Do you have any hints, I need deliver earlier? I'l try with OF 8.4, but cannot seem to find the release tar in the main site. 
Thanks anyway, this is an awesome addons.

**Comment by kashimAstro** [comment]
[kit_mcp.zip](https://github.com/kashimAstro/ofxGPIO/files/403764/kit_mcp.zip)

Hi @xumo 

a simple solution without changing the version is to use the demon that you find in the zip writing in a socket are also an example openFrameworks to read socket.

Good day

**Comment by xumo** [comment]
Yei, thanks a lot.

**Comment by kashimAstro** [comment]
Hi guys @urbanpixellab @xumo, 

I think I've solved the problem with SPI.

good day

**Comment by xumo** [comment]
That's great. I'll test it as soon as I can.
