### ISSUE TITLE
Issue with a raspberry 3 B+

### ISSUE THREAD

**Issue by Taprik** [kashimAstro/ofxGPIO#5]
Hello,

I've tried some of the examples of the ofxgpio and I have some issues with the simple ones.
I'm using a raspberry 3 B+ with of 0.9.3.
It compiles very well.
The simple button example runs perfectly.
But None of the simple led or the relay example. 
When I check the tension between the gpio pin and the ground it stays at 0V.

Actually I managed to blink a led with command line I found at
http://www.blaess.fr/christophe/2012/11/26/les-gpio-du-raspberry-pi/
Here is the result in the terminal
![2016-06-13-194431_1824x984_scrot](https://cloud.githubusercontent.com/assets/5664204/16021176/8d463a40-31b1-11e6-9711-8de4983f38c8.png)
I'm a beginner, but it seems to be the same code as in the addon.
Did I miss something ?

**Comment by kashimAstro** [comment]
I just did a test and it looks like it works.
make sure the pins are free, always making unexport_gpio exit the program.

launch the program as superuser with: sudo ./bin/example-simple-led

you can check whether resources are released by controlling the folder:
ls /sys/class/gpio/

good day

**Comment by Taprik** [comment]
Thank you Kashim,

You're right, it works with sudo ./bin/example-simple-led
I've also found this tricks to authorize permissions for pi
https://www.raspberrypi.org/forums/viewtopic.php?f=44&t=8999

Cheers

**Comment by kashimAstro** [comment]
usually I do not recommend to change the permissions on the folder sys, for his ties to kernel mode.

but it can be done easily if you know your system.
even by simply using:

chmod 777 namedeviceorfile
or
chown pi: pi namedeviceorfile

good day
