### ISSUE TITLE
Can't write to pins on RPI Zero

### ISSUE THREAD

**Issue by bensnell** [kashimAstro/ofxGPIO#7]
Running the example-simple-led produces no change in voltage on GPIO 17. When I change this pin in the code, there is still no voltage output (it stays at Ground).

However, reading the state of a digital pin **does** work, using example-simple-button.

I'm using a Raspberry Pi Zero with Rasbian Jessie Lite.

**Comment by bensnell** [comment]
Apologies. This is the same as issue #5 .

**Comment by kashimAstro** [comment]
Hi @bensnell sorry for delay, they are out for work.
I have to update the README to clarify this and other points.
