### ISSUE TITLE
only works with delay after export_gpio()

### ISSUE THREAD

**Issue by krisrok** [kashimAstro/ofxGPIO#8]
while trying to get the simple led example to work on rpi3 i found i need to add a `ofSleepMillis(100);` after `gpio17.export_gpio();`.

otherwise the pin does not react.

**Comment by kashimAstro** [comment]
This is very strange, make sure you do unexport when you exit the program, and run the track as the superuser or (appropriate permissions).

check the folder: 
/sys/class/gpio/ 
to check if the pin number 17 has been removed.

I am working on robot swarms during this time and use ofxGPIO for motor control and sensors used on "RaspberryPi 2/3 and zero", without problems.

On what operating system are you working on?
and "OF" version are you using?

you have tried to use ofxGPIO without openFrameworks, the result is the same?

thanks and good day!
