### ISSUE TITLE
error open frameworks compiling with window

### ISSUE THREAD

**Issue by viniciolindo** [kashimAstro/ofxGPIO#9]
i have this error when i compile simple button example with windows

obj/linuxarmv6l/Release/src/ofApp.o:(.data+0x0): multiple definition of `OLEDFont'
obj/linuxarmv6l/Release/src/main.o:(.data+0x0): first defined here
collect2: error: ld returned 1 exit status

**Comment by kashimAstro** [comment]
Hi @viniciolindo,
I tried to compile now the example-simple-led for openFrameworks, and seems to be successful.

Reported error, it seems to incriminate a double definition within the file ofApp, the basic example does not use ofApp.h and ofApp.cpp but it's all written in src/main.cpp. you confirm??

![simpleled](https://cloud.githubusercontent.com/assets/6746680/22652617/685a3c4a-ec87-11e6-949f-920d76928bbf.png)

thanks for the tip..

**Comment by viniciolindo** [comment]
I'm working with ofApp.cpp and ofApp.h separated. 
I test that if import only gpio.h instead ofxGPIO.h it compile without error

**Comment by kashimAstro** [comment]
ok, I made a patch that solved the dual includes.

check this:
https://github.com/kashimAstro/ofxGPIO/blob/master/src/font.h#L100

let me know if this solves the problem..

thanks and good day
